# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

generatePredictedPoints_pandemicC <- function(M, chains, horizon, NA_rep, model_name, final_time, nWaves, s_code) {
    .Call(`_PandemicLP_generatePredictedPoints_pandemicC`, M, chains, horizon, NA_rep, model_name, final_time, nWaves, s_code)
}

